spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Auth
    username: root
    password: root@2021
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true